#!/usr/bin/env bash

set -e
git submodule sync --quiet --recursive
git submodule update --init --recursive

sudo ./dotbot/bin/dotbot -p dotbot_plugin_aptget/aptget.py --plugin-dir dotbot-vscode -p my-plugins/snap.py -p dotbot-golang/go.py -d "${BASEDIR}" -c install-priv.conf.yaml "${@}"
./dotbot/bin/dotbot -p dotbot_plugin_aptget/aptget.py --plugin-dir dotbot-vscode -p my-plugins/snap.py -p dotbot-golang/go.py -d "${BASEDIR}" -c install.conf.yaml "${@}"
